import { WORLD_COUNTRY_SET } from '@/constants/world-countries';

/** Maps country / picker labels to primary recipe language keys used across the app. */
export const languageAliasByCountry: Record<string, string> = {
  Afghanistan: 'Persian',
  Albania: 'English',
  Algeria: 'Arabic',
  Argentina: 'Spanish',
  Armenia: 'English',
  Australia: 'English',
  Austria: 'German',
  Azerbaijan: 'Turkish',
  Bahrain: 'Arabic',
  Bangladesh: 'বাংলা',
  Belarus: 'Russian',
  Belgium: 'French',
  Brazil: 'Portuguese',
  Brunei: 'English',
  Cambodia: 'English',
  Cameroon: 'French',
  Canada: 'English',
  Chile: 'Spanish',
  China: 'Chinese',
  Colombia: 'Spanish',
  'Costa Rica': 'Spanish',
  Croatia: 'English',
  Cuba: 'Spanish',
  Czechia: 'English',
  Denmark: 'English',
  Ecuador: 'Spanish',
  Egypt: 'Arabic',
  Ethiopia: 'English',
  Finland: 'English',
  France: 'French',
  Germany: 'German',
  Greece: 'Greek',
  Guatemala: 'Spanish',
  Haiti: 'French',
  Honduras: 'Spanish',
  Hungary: 'English',
  Iceland: 'English',
  India: 'Hindi',
  Indonesia: 'English',
  Iran: 'Persian',
  Iraq: 'Arabic',
  Ireland: 'English',
  Israel: 'English',
  Italy: 'English',
  Jamaica: 'English',
  Japan: 'Japanese',
  Jordan: 'Arabic',
  Kazakhstan: 'Russian',
  Kenya: 'English',
  Korea: 'Korean',
  Kuwait: 'Arabic',
  Laos: 'English',
  Lebanon: 'Arabic',
  Libya: 'Arabic',
  Malaysia: 'English',
  Mexico: 'Spanish',
  Morocco: 'Arabic',
  Myanmar: 'English',
  Nepal: 'English',
  Netherlands: 'English',
  'New Zealand': 'English',
  Nigeria: 'English',
  'North Korea': 'Korean',
  Norway: 'English',
  Oman: 'Arabic',
  Pakistan: 'Urdu',
  Peru: 'Spanish',
  Philippines: 'English',
  Poland: 'English',
  Portugal: 'Portuguese',
  Qatar: 'Arabic',
  Romania: 'English',
  Russia: 'Russian',
  'Saudi Arabia': 'Arabic',
  Serbia: 'English',
  Singapore: 'English',
  'South Africa': 'English',
  'South Korea': 'Korean',
  Spain: 'Spanish',
  'Sri Lanka': 'English',
  Sweden: 'English',
  Switzerland: 'French',
  Syria: 'Arabic',
  Taiwan: 'Chinese',
  Tanzania: 'English',
  Thailand: 'English',
  Tunisia: 'Arabic',
  Turkey: 'Turkish',
  Uganda: 'English',
  Ukraine: 'English',
  'United Arab Emirates': 'Arabic',
  'United Kingdom': 'English',
  'United States': 'English',
  Uruguay: 'Spanish',
  Venezuela: 'Spanish',
  Vietnam: 'English',
  Yemen: 'Arabic',
  Zimbabwe: 'English',
};

const CORE_LANGUAGE_SET = new Set<string>([
  'বাংলা',
  'English',
  'Hindi',
  'Arabic',
  'French',
  'Spanish',
  'Urdu',
]);

export function resolveUiLanguageKey(selectedLang: string): string {
  const raw = selectedLang.trim();
  if (languageAliasByCountry[raw]) return languageAliasByCountry[raw];
  if (CORE_LANGUAGE_SET.has(raw)) return raw;
  if (WORLD_COUNTRY_SET.has(raw)) return 'English';
  return raw;
}
